# Settings.yml
---
conf.py:
  copyright: since 2009
  project: Developing TYPO3 Extensions with Extbase and Fluid
  version: latest
  release: latest
  html_theme_options:
    github_repository: TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid
    github_branch: latest
...
