# Settings.yml
---
conf.py:
  copyright: since 2009
  project: Developing TYPO3 Extensions with Extbase and Fluid
  version: 4.7
  release: 4.7
  html_theme_options:
    github_repository: TYPO3-Documentation/TYPO3CMS-Book-ExtbaseFluid
    github_branch: 4-7
...
